name: "Bug report 🐞"
description: Create a report to help us improve
title: bug/ {{ summarize the reported bug here }}
type: Bug
labels:
  - "bug report 🐞"
assignees:
  - commitybyguardia
projects:
  - "guardiafinance/3"
  - "guardiafinance/4"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Provide a detailed description of the bug you encountered...
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe what you expected to happen instead...
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Paste or attach screenshots here...
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        In some cases we may need more details, so please consider sharing this information with us below.

        > [!NOTE]
        > We will only contact you if it is absolutely necessary. To follow the progress of the issue, you can follow it here on Github
  - type: input
    id: slack-username
    attributes:
      label: Slack Username
      description: We will use this Slack username onto [Comm.ity by Guardia](https://commitybyguardia.slack.com) to contact you if we need more info.
      placeholder: ex. @joao.silva
    validations:
      required: false
  - type: input
    id: email
    attributes:
      label: Email for contact
      description: We will use this email to contact you if we need more info.
      placeholder: ex. email@example.com
    validations:
      required: false
