name: Sync labels

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run in dry-run mode without making changes"
        required: false
        type: boolean
        default: false

permissions:
  issues: write
  pull-requests: write

jobs:
  sync-labels:
    uses: guardiafinance/project-automations/.github/workflows/reusable-label-sync.yml@main
    with:
      delete_other_labels: true
      dry_run: ${{ inputs.dry_run || false }}
    secrets:
      token: ${{ secrets.GH_PROJECT_TOKEN }}
        