name: Verify Signed Commits

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  verify-signatures:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write  # Required to comment on PR

    steps:
      - name: Check signed commits in PR
        uses: 1Password/check-signed-commits-action@v1
        with:
          comment: |
            ⚠️ One or more commits in this Pull Request **are not signed**.
            To ensure security and traceability, all commits must be digitally signed.

            Check out Guardia's tutorial to learn how to sign your commits:
            👉 https://hub.guardia.finance/en/docs/tutorials/signing-commits/
